ReeceSouks/rent-a-plane

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

created navbar for homepage

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_dateform.html.erb

Finished the banner with cool font and image.

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

edit navbar colors and logo on homepage

---

app/views/shared/_banner.html.erb

Added a cool form to the banner, will go back to it later to make it nicer.

Added form to banner.

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb

created footer for homepage

---

app/views/shared/_banner.html.erb

edited some form texts.

---

app/views/shared/_banner.html.erb

changed the font color from black to white.

changed font color.

---

app/controllers/application_controller.rb
app/models/airplane.rb
app/models/booking.rb
app/models/review.rb
app/models/user.rb
config/initializers/devise.rb
db/migrate/20191028090435_create_airplanes.rb
db/migrate/20191028090853_create_bookings.rb
db/migrate/20191028091234_create_reviews.rb
db/migrate/20191028092153_add_first_name_to_users.rb
db/migrate/20191028093251_change_date_columns.rb
db/schema.rb
test/models/airplane_test.rb
test/models/booking_test.rb
test/models/review_test.rb

Added Models and data migration

Added Models and Data Migration

---

app/controllers/airplanes_controller.rb
app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/controllers/users_controller.rb
app/views/airplanes/create.html.erb
app/views/airplanes/destroy.html.erb
app/views/airplanes/edit.html.erb
app/views/airplanes/index.html.erb
app/views/airplanes/new.html.erb
app/views/airplanes/show.html.erb
app/views/airplanes/update.html.erb
app/views/bookings/create.html.erb
app/views/bookings/destroy.html.erb
app/views/bookings/show.html.erb
app/views/reviews/create.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/airplanes_controller_test.rb
test/controllers/bookings_controller_test.rb
test/controllers/pages_controller_test.rb
test/controllers/reviews_controller_test.rb
test/controllers/users_controller_test.rb

adding controllers and views

---

Gemfile
Gemfile.lock
db/seeds.rb

Made a bunch of fake data for our seed.

made a faker seed file.

---

app/controllers/airplanes_controller.rb
app/views/airplanes/index.html.erb

Airplane controllers

---

app/controllers/airplanes_controller.rb
app/models/booking.rb
app/views/airplanes/show.html.erb

made show for airplanes, added reviews to airplanes controller, lastly added has many reviews to bookings model.

made show for airplanes

---

app/controllers/airplanes_controller.rb
app/views/airplanes/index.html.erb
app/views/airplanes/new.html.erb
app/views/shared/_banner.html.erb

1. Adding some code inside index and show method on AirplanesController
2. Linking the submit button on homepage to display airplanes, need styling on font color, from white it turns blue (have to fix it!)

edits on airplane controller and view

---

app/views/airplanes/index.html.erb

small changes, swithcing branch

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/views/shared/_banner.html.erb
app/views/shared/_navbar.html.erb

changed homepage

---

db/seeds.rb

Took beautiful out the faker airplane seed

changed seed.  Took beautiful out plane names.

---

app/views/shared/_banner.html.erb

just changed homepage picture.

---

app/assets/stylesheets/components/_card.scss
app/views/airplanes/index.html.erb

added cards to airplane index page.

added beautiful cards to airplane index.

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/airplanes_controller.rb
app/views/shared/_navbar.html.erb

1. Links navbar button to route path
2. Add some if else condition in navbar css code so the text color will be different when you are on an active directory

link navbar to path routes

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_fonts.scss
app/views/airplanes/index.html.erb
app/views/shared/_banner.html.erb
app/views/shared/_card.html.erb

made font change, changed sentence on pages.

made a font change, some airplanes index page changes.

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/views/airplanes/index.html.erb

Changed all font to montserrat.  Centered h1 on airplane index page.

changed font, and centered h1

---

app/views/shared/_navbar.html.erb

1. User when not signed in cannot have add listing, profile, sign out and retrieve bookings button on navbar
2. User when signed in does not have log in and sign up button on their navbar

user have trips and add listing button when signed in

---

app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/shared/_navbar.html.erb
app/views/users/profile.html.erb
config/routes.rb

1. Change routes because some routes are useless
2. User will be redirected back after signed in to airplanes#show when they try to reserve but havent sign in
3. Redirect trips button on navbar to show future bookings

some changes in routes, views, controller

---

app/controllers/reviews_controller.rb
app/views/bookings/index.html.erb
config/routes.rb

ended the review controllers class, routes to destroy booking is still messed up

ended the review controllers

---

app/views/bookings/index.html.erb
app/views/bookings/show.html.erb

Now user can cancel a booking, please add some front end

last changes

---

app/views/airplanes/show.html.erb

Made a default picture for airplane.  If no picture uploaded.  Show default image.

fixed image problem at airplane show.

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_colors.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

css for log in form

---

app/views/bookings/index.html.erb

Small change to booking index page.  Split upcoming trips and previous trips into 2 coloumns.

Small change to booking index page.

---

app/views/users/profile.html.erb

Small change to booking show added padding and margin to make it look a little nicer/spaced.

Small change to booking show.

---

Gemfile
Gemfile.lock
app/controllers/airplanes_controller.rb
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/controllers/users_controller.rb
app/policies/airplane_policy.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/review_policy.rb
app/policies/user_policy.rb
app/views/bookings/show.html.erb
test/policies/airplane_policy_test.rb
test/policies/booking_policy_test.rb
test/policies/review_policy_test.rb
test/policies/user_policy_test.rb

Added pundit so that reviews can only be controlled by person who booked and flew.

Added pundit for authorizations.

---

app/views/bookings/index.html.erb
app/views/users/profile.html.erb

Actually added card to user profile.  So the Airplane is in same card as my bookings.

just saving so no conflicts.

---

app/views/bookings/index.html.erb

made booking index links more informative.

made booking index more informative.

---

app/assets/stylesheets/pages/_booking.scss
app/views/bookings/index.html.erb

Added a background, kinda made cards for all bookings, booking page is now way more appealing.

made booking index page beautiful.
